### ISSUE TITLE
Netlify deploy error: 404.html[AstroUserError] Unsupported image format "svg"

### ISSUE THREAD

**Issue by gxjansen** [mearashadowfax/ScrewFast#134]
I'm not 100% sure if this is a pure Netlify issue or something with the template, but they don't work together :).

I understand that "runs on Netlify" is a not a promise made by the template or anything, but just in case you're interested, this is how you can reproduce:

1. Clone repo (main or monolingual branch (same result))
2. `npx @astrojs/upgrade `
3. `npx astro add netlify`
4. `npm run astro check` (will result in 0 errors and 0 warnings)
5. Deploying locally: works as expected
6. Deploying to Github pages: works as expected
7. Deploying to Vercel: works as expected
8. Deploying to Netlify will result in an error:

```
9:38:26 PM: 19:38:26 ▶ src/pages/404.astro
9:38:26 PM: 19:38:26   └─ /404.html[AstroUserError] Unsupported image format "svg"
9:38:26 PM:   Hint:
9:38:26 PM:     Use one of avif, jpg, png, webp instead.
9:38:26 PM:   Stack trace:
9:38:26 PM:     at Object.validateOptions (file:///opt/build/repo/node_modules/@astrojs/netlify/dist/image-service.js:32:19)
9:38:26 PM:     at async getImage (file:///opt/build/repo/dist/chunks/_astro_assets_BfOTnQq2.mjs:989:42)
```
Full log in the attachement (error starts at line 159)
[log.txt](https://github.com/user-attachments/files/16102410/log.txt)

Haven't been able to solve it yet

**Comment by mearashadowfax** [comment]
Hi @gxjansen! Thanks for bringing this issue to my attention. I believe I’ve identified the problem. In the [Meta.astro](https://github.com/mearashadowfax/ScrewFast/blob/main/src/components/Meta.astro) component, we are importing `faviconSvgSrc` in the frontmatter:
 
```
---
import faviconSvgSrc from "@images/icon.svg";
---
``` 
Then we generate and optimize it:

```
const faviconSvg = await getImage({
  src: faviconSvgSrc,
  format: "svg",
});
```

And use it as follows:

```
<link href={faviconSvg.src} rel="icon" type="image/svg+xml" sizes="any" />
```

It seems that Netlify’s image service is having trouble importing this SVG, or there might be another issue at play. I hadn't deployed it to Netlify before, but after attempting it now, I encountered the same error as you did. After removing all occurrences of `faviconSvgSrc`, the deployment worked successfully on both branches.

Since it works on other platforms, I’ll maintain the current implementation. However, I will add a note in the README file suggesting to use:
```
<link href="/icon.svg" rel="icon" type="image/svg+xml" sizes="any" />
```
with the icon located in the public folder, this should resolve the issue for Netlify deployments.

**Comment by gxjansen** [comment]
That solved the SVG error @mearashadowfax, thx!
