### ISSUE TITLE
License obtained to use Strabag, Hochtief, Vinci, and DPR logos?

### ISSUE THREAD

**Issue by corndog2000** [mearashadowfax/ScrewFast#255]
Hello, I found this template through a friend. But, it does not appear that this project has licenses for the logos of Strabag, Hochtief, Vinci, and DPR. This could be an issue with someone associating this fake website with these real companies.

**Comment by mearashadowfax** [comment]
Hey @corndog2000! Thank you for bringing this up. I've added a disclaimer in the README file clarifying that there is no official association with these companies. Since this is an open-source, non-commercial website template, I believe this use falls under fair use for demonstration purposes, but I appreciate your concern and attention to detail.
